name: Linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline: 
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [ 17.x ]
    steps: 
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: run eslint
        run: npm run eslint
      - name: run stylelint
        run: npm run stylelint
      - name: run unit tests
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
      - name: upload storybook build files
        uses: actions/upload-artifact@v3
        with:
          name: storybook-build
          path: ./storybook-static
      - name: screenshot testing
        run: npm run test:ui:ci
      - name: upload screenshot testing files
        uses: actions/upload-artifact@v3
        with:
          name: screenshots from loki
          path: ./.loki
        